version: '2'
services:
  graphite:
    build: graphite
    restart: always
    container_name: gamergraf-graphite
    ports:
        - "8000:8000"
        - "2003:2003"
        - "2004:2004"
    volumes:
        - "/mnt/user/appdata/graphite/data/storage/:/opt/graphite/storage/"